# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import tensor_parallel_pb2 as tensor__parallel__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in tensor_parallel_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TensorParallelServiceStub(object):
    """Service for tensor parallel computation
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ComputeMatMul = channel.unary_unary(
                '/tensor_parallel.TensorParallelService/ComputeMatMul',
                request_serializer=tensor__parallel__pb2.ComputeRequest.SerializeToString,
                response_deserializer=tensor__parallel__pb2.ComputeResponse.FromString,
                _registered_method=True)


class TensorParallelServiceServicer(object):
    """Service for tensor parallel computation
    """

    def ComputeMatMul(self, request, context):
        """Computes a matrix multiplication slice
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TensorParallelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ComputeMatMul': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeMatMul,
                    request_deserializer=tensor__parallel__pb2.ComputeRequest.FromString,
                    response_serializer=tensor__parallel__pb2.ComputeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tensor_parallel.TensorParallelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tensor_parallel.TensorParallelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TensorParallelService(object):
    """Service for tensor parallel computation
    """

    @staticmethod
    def ComputeMatMul(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tensor_parallel.TensorParallelService/ComputeMatMul',
            tensor__parallel__pb2.ComputeRequest.SerializeToString,
            tensor__parallel__pb2.ComputeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
